authentik:
    secret_key: "4comjFvInuKxutjwulQsyEva2qBhS+4kT7JjyjOAzz4dh93tgMXzo68thhNt0O5n/2poB9viRUqDOFsF"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "Z55s072Q0YU0cxMqK/A16hE190q77DSOS5VhtgTXNxYehzWPLMeW7yN/+9fgs4rOtpiDiRvT5V08kVHv"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        enabled: false
        hosts:
            - authentik.domain.tld

postgresql:
    enabled: true
    auth:
        password: "OMEwEwE+CaT2Vdppdv61fbwzVINOsPDyNqOh6WflpXFb+x98xtehXh0XAZppEOVsU85OBUBMT+hqPNpz"
redis:
    enabled: true